### ISSUE TITLE
Split anthology to enhance index/convert process

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#111]
Indexation/conversion is a bit tedious for the moment: one has to index and convert a repository. This leads to two commits (repository and .-full-build).
# Proposal:
- anthology in .full-build repository won't contain anymore project definitions
- each repository will have a .full-build folder with only the definition of its own projects
  - Graph will use a consolidated project definitions from .full-build\bin\projects
  - push process will generate consolidated project definitions
  - convert process will update consolidated project definitions
## CCI side

When artifacts are pushed (the one living under .full-build\bin), anthology consolidation will take place: all available repositories will be used to update the existing consolidated anthology.
## developer side

When conversion takes place, consolidated project definitions will be impacted with new projects.

Note that if projects are removed or added, this will require to have all repositories cloned to perform a global indexation because a package could be removed and promoted to projet. This will require the "consolidated" anthology to be split apart then.

# TODO
- [x] projects into .full-build\anthology will be removed
- [x] convert must consolidate converted repositories in .full-build\bin\projects
- [x] convert must generate project definitions in repository\.fbprojects - impacted repositories must be cloned otherwise this must fail
- [x] push must consolidate all projects of repositories in .full-build\bin\projects before pushing (UNDONE - only on pull, clone & branch)
- [x] Graph will load project definitions from .full-build\bin\projects
- [x] Consolidate anthology on pull & checkout
- [x] Implement anthology consistency check (command index --help) : index all local repositories and check if .fbprojects is different than persisted one

**Comment by pchalamet** [comment]
will be shipped in 3.2
