### ISSUE TITLE
Change baseline implementation

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#114]
Current problems with baseline is that CI must push sources to .full-build repository leading to merge sometimes.

Baseline could be implemented using tags.
And considering tags are immutable (well at least should) and unique, no clash/merge could happen.

Also, this would be easier for users to checkout a version (using tag name instead of version hash).

# Baselines
A tag will be applied on *all* repositories. This tag will have from : fullbuild-<branch>-<version>
If a single repository is missing then the baseline can't be applied and an error will be raised.

# Get corresponding binaries
Binaries are linked to current branch. Command "branch" has to be modified to store the current branch. Default repository branch will provide default setting.

When binaries must be fetched, the branch info will be consulted and used to get matching binaries.

# Git commands
find latest annotated tag:
    git describe --match "fullbuild-master-*"

set annotated tag:
    git tag -a fullbuild-master-42 -m "bookmark"

find hash of tag (with comment):
    git rev-list --format="%H %s" -n 1 fullbuild-master-42

history from tag
    git log fullbuild-master-42..HEAD

# TODO
  - [ ] Implement Baselines using tags
  - [ ] Branch command store in .full-build\bin\branch the branch name
  - [ ] Fetching binaries will use branch info

**Comment by pchalamet** [comment]
On hold - baseline is heavily used for partial build - and that's the only reliable way to find the latest build baseline.

**Comment by pchalamet** [comment]
Baseline can be found as follow:
* Find matching hash in versions history
* Get latest tag on this hash
* Checkout baseline using this tag

**Comment by pchalamet** [comment]
Basically implemented (branch v3.2)
Have to do a lot of testing as a lot of code as moved around.
