### ISSUE TITLE
static view support

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#122]
# Problem

In current implementation, views are dynamic and can't be shared across teams. This is deliberated in order to avoid dead structure in place - which solution file encourage (this is why sln files are removed in conversion step). Moreover dynamic view permits selecting dependencies are consuming projects which is useful for debugging or refactoring at large.

But, sharing across team is important as this can act as anchors to well known business case.
Some examples:
- a framework made of several modules
- an application 

Static view could be committed within a repository. This is - and must be - kept foreign as this can't be considered stable. It will have same drawbacks as solution file and maintenance will be inevitable in long term. But it's a valid tradeoff to offer an easy access to bunch of projects.

## Interaction details

- static view will be materialized as a file (committable) using "add view"
- extension will be registered by full-build allowing user to double-click to quickly open it from shell
- static view can't be used with commands expecting a (dynamic) view

## safety net

  * static view won't be stored inside dynamic views repository
  * static view will have a custom file format, decoupled from dynamic view
  * if a static failed to generate a valid solution file, error should be reported correctly upon launch

# Implementation steps

- [x] add view command will support '--static' argument
- [x] view command will generate a static view definition in _current folder of a valid repository_ under name _viewName.fbsln_
- [x] register file extension on install
- [x] file extension handler : generate dynamic view with stored information of static view and open dynamic view

**Comment by pchalamet** [comment]
This is formalization of issue #100

**Comment by sergii-s** [comment]
Can a static view be an argument in a commands like fb build, fb test, fb publish ?

**Comment by pchalamet** [comment]
good question... Hard to say without determining if we can list or not.
If we can list, it's easy. If not it should not probably.

2 problems I see:
  * should a static view name be unique ? Considering only cloned repositories, this could not be a problem to only fail if more than one found.
  * how to list static views ? Scan all directories ?

**Comment by pchalamet** [comment]
But is that really a problem frankly ?

The goal here is to have persistent "shortcuts" to dynamic view to help opening solution quickly.
If the dynamic view is generated behind, everything will be compatible anyway....

**Comment by pchalamet** [comment]
And considering target users, it's better to bet on VS add-in to brought those functionalities (updated issue)

**Comment by sergii-s** [comment]
In my opinion dynamic views could be totally replaced by the statics (as in the proposed PR). The only difference of the behavior is that adding view creates a view file in the current folder and not in the views folder(and I think it's better than --static option). All others commands(open, build etc) also take into account current path, but it could be improved(f/ex having the reference to view file from the views folder)

**Comment by pchalamet** [comment]
mostly implemented - will track enhancements in other issues.
